env: dev

logging:
  dev:
    level: DEBUG
    console: true
    file: logs/dev.log
    rotation: 5 MB
    retention: 7 days

  test:
    level: WARNING
    console: true
    file: logs/test.log

  prod:
    level: INFO
    console: true
    file: logs/app.log
    rotation: 10 MB
    retention: 30 days
    compression: zip
